### ISSUE TITLE
Odd extra zero pairs between entries in dmi_table buffer

### ISSUE THREAD

**Issue by fernLightning** [cavaliercoder/dmidecode-osx#2]
Using ./dmidecode I get about 40 of the 42 structures before getting a:
Invalid entry length (0). DMI table is broken! Stop.

Investigating the raw buffer I discover that the last few entries are separated by multiple pairs of zeros, rather than the expected one pair.  To address this oddity I changed:

in dmidecode.c:dmi_table_decode(..)

``` c
        /* look for the next handle */
        next = data + h.length;
        while ((unsigned long)(next - buf + 1) < len
               && (next[0] != 0 || next[1] != 0)) {
            next++;
        }
        next+=2;
```

Replacing the final next+=2 with:

``` c
        while((unsigned long)(next - buf + 1) < len && (next[0] == 0 && next[1] == 0)) {
            next+=2;
        }
```

MacBookAir6,1 - osx 10.11.2
I've attached a zip of '--dump-bin' file so you can try it yourself.

[air.raw.zip](https://github.com/cavaliercoder/dmidecode-osx/files/92773/air.raw.zip)

**Comment by onixsosx** [comment]
can you elaborate more on this. as the source is not matched to your changes.

source as of Oct. 20,2015:
`/* look for the next handle */
        next = data + h.length;
        while ((unsigned long)(next - buf + 1) < len
            && (next[0] != 0 || next[1] != 0))
            next++;
        next += 2;
        if (display)`
Making the changes got me into "Invalid entry length (0). DMI table is broken! Stop"

**Comment by kammoh** [comment]
I had the same issue on a MacBookPro11,2 and the fix proposed by @fernLightning seems to perfectly work. Any chance this could be incorporated into master? Are there variations that need to be considered for other hardware models?

**Comment by cavaliercoder** [comment]
Thanks for taking the time to debug and submit this issue. I'm sorry it took so long to action!
Fixed and updated in the homebrew package.
